#ifndef BOARD_TTGO_H
#define BOARD_TTGO_H

// Pin definitions for TTGO layout
#define CONFIG_TUNER_PIN_VIDEO 32
#define CONFIG_TUNER_PIN_RSSI 33
#define CONFIG_VRX58_PIN_VIDEO 35
#define CONFIG_VRX58_RSSI 34
#define CONFIG_VRX58_PIN_MOSI 23
#define CONFIG_VRX58_PIN_CLK 18
#define CONFIG_VRX58_PIN_CS 5
#define CONFIG_BUZZER_PIN 4
#define CONFIG_BATT_PIN_CARGER 27
#define CONFIG_BATT_PIN 39
#define CONFIG_CD4066_PIN_A 26
#define CONFIG_CD4066_PIN_B 25
#define CONFIG_KEY_PIN 0

#endif // BOARD_TTGO_H
